### ISSUE TITLE
Can't enable or remove plugin

### ISSUE THREAD

**Issue by kedare** [Piwigo/piwigo-openstreetmap#209]
Hello.

On a new Piwigo setup (v12.1.0)

I can download the openstreetmap plugin (same behaviour from doing a git clone also), but when activating it, I get an error and this in the logs

```
2022/01/26 17:38:02 [error] 3981935#3981935: *29001 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'piwigo-openstreetmap_maintain' not found in /var/www/piwigo/admin/include
/plugins.class.php:81
Stack trace:                                                                                                                                                                                                
#0 /var/www/piwigo/admin/include/plugins.class.php(113): plugins::build_maintain_class('piwigo-openstre...')
#1 /var/www/piwigo/include/ws_functions/pwg.extensions.php(71): plugins->perform_action('activate', 'piwigo-openstre...')
#2 /var/www/piwigo/include/ws_core.inc.php(600): ws_plugins_performAction(Array, Object(PwgServer))
#3 /var/www/piwigo/include/ws_protocols/rest_handler.php(41): PwgServer->invoke('pwg.plugins.per...', Array)
#4 /var/www/piwigo/include/ws_core.inc.php(281): PwgRestRequestHandler->handleRequest(Object(PwgServer))
#5 /var/www/piwigo/ws.php(22): PwgServer->run()
#6 {main}
  thrown in /var/www/piwigo/admin/include/plugins.class.php on line 81" while reading response header from upstream, client: 2a01:e0a:21a:3c01:d622:2379:2ce:50d6, server: piwigo.ynh.keda.re, request: "GET
 /ws.php?method=pwg.plugins.performAction&action=activate&plugin=piwigo-openstreetmap&pwg_token=90b77ded48124b0f40a519dae097f700&format=json HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm-pi
wigo.sock:", host: "piwigo.ynh.keda.re", referrer: "https://piwigo.ynh.keda.re/admin.php?page=plugins&tab=installed"
```

Same error when trying to uninstall it

Any idea on how to fix it ?

Thanks

**Comment by plegall** [comment]
you need Piwigo 12.2.0
