### ISSUE TITLE
Undefined array key "osm_mapquestapi" piwigo-openstreetmap

### ISSUE THREAD

**Issue by jonidimo** [Piwigo/piwigo-openstreetmap#232]
Piwigo version: 13.8
PHP 8.1.2-1ubuntu2.13

Hello, I am using Piwigo with the openstreetmap plugin on Ubuntu 22.04.2 LTS. This is a fresh install. When I try to save the the plugin settings, I get the following error:

Warning: Undefined array key “osm_mapquestapi” in /var/www/html/piwigo/plugins/piwigo-openstreetmap/admin/admin_config.php on line 201

I have tried to solve the problem by defining the variable “osm_mapquestapi” before using it, but I don’t know what's the right way to do it. 

In addition, I have another error when I choose the world map level in the plugin settings. No matter what template I choose (osm-map.tpl, osm-map2.tpl, osm-map3.tpl), I get the following message:

Not Found The requested URL was not found on this server. Apache/2.4.52 (Ubuntu) Server at 192.168.1.42 Port 80

Finally, When I enable "show the map in the main manu" I have this error:

"Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/piwigo/_data/templates_c/d0vo2^2cf037454b3787dfc8c48405af60c86e22542593_0.file.menubar.tpl.php:58 Stack trace: #0 /var/www/html/piwigo/include/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_64b0ddf17bcfa9_17090569() #1 /var/www/html/piwigo/include/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode() #2 /var/www/html/piwigo/include/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render() #3 /var/www/html/piwigo/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render() #4 /var/www/html/piwigo/include/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute() #5 /var/www/html/piwigo/include/template.class.php(469): Smarty_Internal_TemplateBase->fetch() #6 /var/www/html/piwigo/include/template.class.php(392): Template->parse() #7 /var/www/html/piwigo/include/block.class.php(192): Template->assign_var_from_handle() #8 /var/www/html/piwigo/include/menubar.inc.php(380): BlockManager->apply() #9 /var/www/html/piwigo/include/menubar.inc.php(15): initialize_menu() #10 /var/www/html/piwigo/index.php(103): include('...') #11 {main} thrown in /var/www/html/piwigo/_data/templates_c/d0vo2^2cf037454b3787dfc8c48405af60c86e22542593_0.file.menubar.tpl.php on line 58"

**Comment by camillehuot** [comment]
Same issue here. Did you manage to find a fix?

**Comment by jonidimo** [comment]
> Same issue here. Did you manage to find a fix?

No.
